### ISSUE TITLE
URGENT! Impossible to send Native Tokens (iOS and Android)

### ISSUE THREAD

**Issue by TheBHubIO** [Emurgo/yoroi-mobile#1977]
Hello!
[Android & iOS: v4.7.0]
I successfully sent native token to my Yoroi wallet from another wallet, but when I try to send native tokens from Yoroi wallet the fee isn't calculated which leads to the button "Continue" to be disabled.
I believe that the problem comes from the calculation of the fee to send native tokens; I did a "costly" work around by sending all assets (ADA and native token) but you can understand that this is not ideal...

Hope that you can solve it asap.

**Comment by Nebyt** [comment]
Hi @TheBHubIO.
Thank you for your report.
Please, try to change the amount and return the previous amount.
We have been working on a solution to make it work right.

**Comment by TheBHubIO** [comment]
Hi @Nebyt,
Sorry for the late reply... But this solution didn't work. Is it normal that we can't send native tokens?

**Comment by zuzunker** [comment]
> Hi @Nebyt, Sorry for the late reply... But this solution didn't work. Is it normal that we can't send native tokens?

Hi, @TheBHubIO! In mobile or in browser extension?

**Comment by TheBHubIO** [comment]
> 

In mobile

**Comment by zuzunker** [comment]
Ah, this is being investigated at the moment as top priority and we are hoping to get it fixed asap

**Comment by stackchain** [comment]
Hey @TheBHubIO sending native asset issue was fixed on `4.7.16`, it is released on the Apple store, still under review on the Android play store, usually it takes 24h~, also if you are wondering to test the pre-release versions, please share your email with our support team, so you can be notified and test all new features that we are adding to Yoroi.

**Comment by TheBHubIO** [comment]
@

> Hey @TheBHubIO sending native asset issue was fixed on `4.7.16`, it is released on the Apple store, still under review on the Android play store, usually it takes 24h~, also if you are wondering to test the pre-release versions, please share your email with our support team, so you can be notified and test all new features that we are adding to Yoroi.

Hello @stackchain , thank you for your reply. I've been waiting for the update on android Play store but I still don't see it. Did the review went through?

**Comment by stackchain** [comment]
> @
> 
> > Hey @TheBHubIO sending native asset issue was fixed on `4.7.16`, it is released on the Apple store, still under review on the Android play store, usually it takes 24h~, also if you are wondering to test the pre-release versions, please share your email with our support team, so you can be notified and test all new features that we are adding to Yoroi.
> 
> Hello @stackchain , thank you for your reply. I've been waiting for the update on android Play store but I still don't see it. Did the review went through?

Hi @TheBHubIO yes the review was approved the current rollout stage is at 50%, and we're gonna be bumping to 75/100 in the next few days.
